version: '3.7'

services:
  scraper:
    build: .
    environment:
      - 'DATABASE_URL=postgres://postgres:postgres@postgres/nebulo_dev'
      - 'REDIS_URL=redis://@redis:6379'
    env_file:
      - '.env'
    volumes:
      - '.:/app'
      - '/app/node_modules'
  postgres:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - './sql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=nebulo_dev'
    ports:
      - '5432:5432'
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
